// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApis.DataDbContext;

#nullable disable

namespace MinimalApis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228072254_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupRoleDetailRoleDetailID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("OutletsId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupRoleDetailRoleDetailID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9efdf2c7-bb67-46f3-9049-5e19163549f0",
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "a2155926-ce85-44cc-8b3f-4e20bf753e7d",
                            DateCreated = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@library.com",
                            EmailConfirmed = true,
                            GroupId = 1,
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@LIBRARY.COM",
                            NormalizedUserName = "ADMIN123",
                            OutletsId = 0L,
                            PasswordHash = "AQAAAAIAAYagAAAAEPJQwqcZcuwQxDZWqDBXHBchr3A/dvykHdPE0H91KlFpJ400UXfxBJsUUjSseTC/yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "176c9de8-fc0b-45ef-ad3e-74b0e83f28ba",
                            TwoFactorEnabled = false,
                            UserName = "Admin123"
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("ACountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CountryID");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            Active = true,
                            CountryCode = "PK",
                            CountryName = "Pakistan",
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyId = 1,
                            ModifyBy = "1",
                            ModifyOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumOfDecimal")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "PKR",
                            CurrencyName = "Pakistani Rupee",
                            IsDefault = true,
                            ModifyBy = "1",
                            ModifyOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumOfDecimal = 2,
                            Rate = 75m
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Employee_Name_EF");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.EntityList", b =>
                {
                    b.Property<string>("EntityCode")
                        .HasColumnType("varchar(25)");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RowNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowNo"));

                    b.HasKey("EntityCode");

                    b.ToTable("EntityLists");

                    b.HasData(
                        new
                        {
                            EntityCode = "Dashboard",
                            Active = true,
                            EntityName = "Dashboard",
                            Icon = "dashboard",
                            IsParent = false,
                            ModuleCode = "Dashboard",
                            OrderNum = 1,
                            Path = "/dashboard",
                            RowNo = 1L
                        },
                        new
                        {
                            EntityCode = "Outlet",
                            Active = true,
                            EntityName = "Outlet",
                            Icon = "store",
                            IsParent = false,
                            ModuleCode = "Outlet",
                            OrderNum = 2,
                            Path = "/outlets",
                            RowNo = 2L
                        },
                        new
                        {
                            EntityCode = "UserProfile",
                            Active = true,
                            EntityName = "UserProfile",
                            Icon = "person",
                            IsParent = false,
                            ModuleCode = "UserProfile",
                            OrderNum = 3,
                            Path = "/profile",
                            RowNo = 3L
                        },
                        new
                        {
                            EntityCode = "Reports",
                            Active = true,
                            EntityName = "Reports",
                            Icon = "report",
                            IsParent = false,
                            ModuleCode = "Reports",
                            OrderNum = 4,
                            Path = "/report",
                            RowNo = 4L
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.EntityListDetailCompanyWise", b =>
                {
                    b.Property<long>("RowNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowNo"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int?>("SubscriptionCompanyID")
                        .HasColumnType("int");

                    b.HasKey("RowNo");

                    b.HasIndex("EntityCode");

                    b.HasIndex("SubscriptionCompanyID");

                    b.ToTable("EntityListDetails");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Expenses", t =>
                        {
                            t.HasCheckConstraint("CK_Expense_Category", "[Category] IN ('Home', 'Personal', 'Family', 'Other')");

                            t.HasCheckConstraint("CK_Expense_Type", "[Type] IN ('Prepaid', 'Postpaid')");
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleDetail", b =>
                {
                    b.Property<int>("RoleDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleDetailID"));

                    b.Property<bool?>("Allow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Edit")
                        .HasColumnType("bit");

                    b.Property<string>("EntityCode")
                        .HasColumnType("varchar(25)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool?>("New")
                        .HasColumnType("bit");

                    b.HasKey("RoleDetailID");

                    b.HasIndex("EntityCode");

                    b.HasIndex("GroupID");

                    b.ToTable("GroupRolesDetails");

                    b.HasData(
                        new
                        {
                            RoleDetailID = 1,
                            Allow = true,
                            Edit = true,
                            EntityCode = "Dashboard",
                            GroupID = 1,
                            New = true
                        },
                        new
                        {
                            RoleDetailID = 2,
                            Allow = true,
                            Edit = true,
                            EntityCode = "Outlet",
                            GroupID = 1,
                            New = true
                        },
                        new
                        {
                            RoleDetailID = 3,
                            Allow = true,
                            Edit = true,
                            EntityCode = "UserProfile",
                            GroupID = 1,
                            New = true
                        },
                        new
                        {
                            RoleDetailID = 4,
                            Allow = true,
                            Edit = true,
                            EntityCode = "Reports",
                            GroupID = 1,
                            New = true
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleMaster", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupID");

                    b.HasIndex("CompanyId");

                    b.ToTable("GroupRolesMaster");

                    b.HasData(
                        new
                        {
                            GroupID = 1,
                            CompanyId = 1,
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupName = "Manager",
                            ModifyBy = "1",
                            ModifyOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Outlet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArabicAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArabicArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArabicOutletName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OutletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutletSequanceNo")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("OutletName", "Email", "CompanyId", "CountryId")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [CompanyId] IS NOT NULL AND [CountryId] IS NOT NULL");

                    b.ToTable("Outlets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Karachi",
                            CompanyId = 1,
                            CountryId = 1,
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyID = 1,
                            Email = "outlet1@gmail.com",
                            IsActive = true,
                            ModifyBy = "1",
                            ModifyOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            OutletName = "Outlet1",
                            Phone = "0341"
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Subscription", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyURLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletsCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PricePlan")
                        .HasColumnType("int");

                    b.HasKey("CompanyID");

                    b.HasIndex("CountryID");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            CompanyID = 1,
                            CompanyName = "Demo Company",
                            ContactPerson = "Abdul",
                            CountryCode = "PK",
                            CountryID = 1,
                            CreatedBy = "1",
                            CreatedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Mobile = "0341",
                            ModifyBy = "1",
                            ModifyOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            OutletsCount = "10"
                        });
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.SubscriptionPaymentDetail", b =>
                {
                    b.Property<int>("SubPaymentDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubPaymentDetailID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OutletID")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubPaymentDetailID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("OutletID");

                    b.ToTable("SubscriptionPaymentDetails");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultOutlet")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupRoleGroupID")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutletIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GroupRoleGroupID");

                    b.ToTable("MainUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApis.Entities.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.AppUser", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Company")
                        .WithMany("AppUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalApis.Entities.Model.GroupRoleMaster", "Group")
                        .WithMany("AppUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinimalApis.Entities.Model.GroupRoleDetail", null)
                        .WithMany("AppUsers")
                        .HasForeignKey("GroupRoleDetailRoleDetailID");

                    b.Navigation("Company");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Country", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Employee", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApis.Entities.Model.AppUser", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.EntityListDetailCompanyWise", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.EntityList", "Entity")
                        .WithMany("CompanyWiseDetails")
                        .HasForeignKey("EntityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Subscription")
                        .WithMany("EntityAccess")
                        .HasForeignKey("SubscriptionCompanyID");

                    b.Navigation("Entity");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleDetail", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.EntityList", "Entity")
                        .WithMany("GroupRoleDetails")
                        .HasForeignKey("EntityCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalApis.Entities.Model.GroupRoleMaster", "GroupRole")
                        .WithMany("RoleDetails")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Entity");

                    b.Navigation("GroupRole");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleMaster", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Subscription")
                        .WithMany("GroupRoles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Outlet", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Subscription")
                        .WithMany("Outlets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MinimalApis.Entities.Model.Country", "Country")
                        .WithMany("Outlets")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MinimalApis.Entities.Model.Currency", "Currency")
                        .WithMany("Outlets")
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Subscription", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Country", "Country")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.SubscriptionPaymentDetail", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MinimalApis.Entities.Model.Outlet", "Outlet")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("OutletID");

                    b.Navigation("Outlet");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.User", b =>
                {
                    b.HasOne("MinimalApis.Entities.Model.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MinimalApis.Entities.Model.GroupRoleMaster", "GroupRole")
                        .WithMany()
                        .HasForeignKey("GroupRoleGroupID");

                    b.Navigation("GroupRole");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.AppUser", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Country", b =>
                {
                    b.Navigation("Outlets");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Currency", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Outlets");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.EntityList", b =>
                {
                    b.Navigation("CompanyWiseDetails");

                    b.Navigation("GroupRoleDetails");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleDetail", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.GroupRoleMaster", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Outlet", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("MinimalApis.Entities.Model.Subscription", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("EntityAccess");

                    b.Navigation("GroupRoles");

                    b.Navigation("Outlets");

                    b.Navigation("Payments");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
